### PR TITLE
Deactivate function added

### PR DESCRIPTION
**Pull request by varinderdhanda**
account deactivation done. Please give a review

### CODE REVIEW

**Review by jagdeepbaidwan — APPROVED** [review]
Looks perfect, servers the purpose.

**Review by puneetsingh3-sysc — APPROVED** [review]
It serves the purpose, but minor indentation problems.

**Review by Arshpreet-Singh38 — APPROVED** [review]
Thats good! Coding convention has been taken care!

**Comment by varinderdhanda** [comment]
thank for your reviews

**Pull request merged**
