### PR TITLE
 Change password function added

### PR DESCRIPTION
**Pull request by jagdeepbaidwan**
Change password functionality has been added for Admin, manager and employee, the function will verify the old password before changing the password

### CODE REVIEW

**Comment by varinderdhanda** [comment]
Your code runs and meets functioning

**Review by varinderdhanda — APPROVED** [review]
meets all function requirements

**Review by puneetsingh3-sysc — APPROVED** [review]
It works fine.

**Review by Arshpreet-Singh38 — APPROVED** [review]
Well implemented!

**Comment by jagdeepbaidwan** [comment]
Thanks for your review guys.

**Pull request merged**
