### PR TITLE
Added two function of attendance month and daily attendance

### PR DESCRIPTION
**Pull request by varinderdhanda**
Added functions of new month creation in the attendance table. and now you are able to add daily attendance

### CODE REVIEW

**Review by puneetsingh3-sysc — APPROVED** [review]
I like the way you made the validations for everything and tries to covers all aspects. Its look good and work fine.

**Review by jagdeepbaidwan — APPROVED** [review]
Looks good.

**Review by Arshpreet-Singh38 — APPROVED** [review]
Very well implemented. Just one clarification, will the attendance in .csv file be assumed to be pre-populated from some attendance system like bio-metric ?

**Comment by varinderdhanda** [comment]
Yes Arsh, it will be pre-populated.

**Pull request merged**
