### PR TITLE
Creating the Main.c function

### PR DESCRIPTION
**Pull request by Arshpreet-Singh38**
Please review the main function.This function will form the base structure to proceed with admin,employee and manager functionalities depending on the user inputs.

### CODE REVIEW

**Review by jagdeepbaidwan — APPROVED** [review]
Its seems perfect to me.

**Comment by varinderdhanda** [comment]
Code seems good and all functioning is done by the function

**Review by varinderdhanda — APPROVED** [review]
Code seems good and all functioning is done by the function

**Comment by puneetsingh3-sysc** [comment]
Code is working but minor indentation problem.

**Pull request merged**
